steps:
- name: 'gcr.io/kaniko-project/executor:v1.22.0'
  env: ['REVISION_ID=$REVISION_ID']
  args:
  - --destination=gcr.io/$PROJECT_ID/harana.dev:$REVISION_ID
  - --cache=true
  - --cache-ttl=336h
  - --build-arg=REVISION_ID
  timeout: 2400s
# copy the compiled assets from the docker container to the workspace to then push to GCS
- name: 'docker'
  args: ['run', '-v', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/harana.dev:$REVISION_ID', 'cp', '-R', '/harana.dev/public/assets/', '/workspace/']
  timeout: 2400s
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', '/workspace/assets/', 'gs://libraries-static-assets/']
  timeout: 2400s
timeout: 4800s
