volumes:
  postgres-data:
    driver: local

  redis-data:
    driver: local

  elasticsearch-data:
    driver: local

services:
  postgres:
    image: postgres:9.6.24
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=not-a-secret
      - POSTGRES_USER=librariesio
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:8.13.4
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false

  redis:
    image: redis:7
    volumes:
      - redis-data:/var/lib/redis
    command: redis-server --appendonly yes

  sidekiq: &app_base
    build:
      context: .
    image: haranaoss/lio:1
    environment:
      - DATABASE_URL=postgresql://librariesio:not-a-secret@postgres/librariesio
      - REDISCLOUD_URL=redis://redis:6379/1
      - ELASTICSEARCH_CLUSTER_URL=elasticsearch:9200
    volumes:
      - .:/libraries.io
    depends_on:
      - postgres
      - elasticsearch
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml

  web:
    <<: *app_base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server --port 3000 --binding '0.0.0.0'"
    ports:
      - "3000:3000"
